services:
  strapi:
    build:
      context: ./strapi
    container_name: strapi-app
    ports:
      - "1337:1337"
    volumes:
      - ./strapi:/srv/app:cached
      - /srv/app/node_modules
    environment:
      - NODE_ENV=development
